### BotPEASS Configuration Settings

# Search & Filtering Behavior
ALL_VALID: no

# Set your primary scope of CVE's to include for notifications
# Configure this as one of: all_cves, all_keywords, products
#   - all_cves:       every CVE in the results will be sent as a message
#   - all_keywords:   All CVE's matching your defined keywords will be sent (including products)
#   - products:       Only CVE's matching your defined products, but you get all of them, regardless of keywords
SEARCH_SCOPE: products

#user:admin
#password:admin
#api token

# -- Include High-Severity CVE's Always --
# Expand your search scope to also include high-severity CVE's
# NOTE: Out of caution, if enabled, bot will also include all CVE's for which no score exists yet, so we don't
# miss a hot new CVE that just doesn't yet have a score assigned.
#     True:         enabled
#     threshold:    all CVE's with CVSS score equal to or higher are included
INCLUDE_HIGH_SEVERITY: True
HIGH_SEVERITY_THRESHOLD: 10.0

# -- Exclude Low-Severity CVE's Always --
# Enable including only matched keywords if CVE is also a high CVSS score (reduce noise of low-severity CVE's)
# Disclaimer: If enabled, this means you will not see CVE's for which the CVSS score is currently blank
ENABLE_SCORE_FILTERING: True
MIN_SCORE_THRESHOLD: 7.0

# -- MITRE Exploit-DB -- Update dataset every 'n' days
MITRE_INTERVAL: 3

# -- EPSS Score Lookups --
ENABLE_EPSS_LOOKUPS: True

# -- Exclusion Filtering --
# If present, exclude CVE from results
# NOTE: Case Sensitive!
EXCLUDED_KEYWORDS:
- SourceCodester
- Sourcecodester
- Reservation System 1.0
- Reservation-System 1.0

# Case-insensitive keywords in CVE Description/Summary
DESCRIPTION_KEYWORDS_I:
#- auth bypass
#- authentication bypass
#- default credentials
#- default password
#- deserialization
#- sql injection
#- privesc
#- local file inclusion
#- remote file inclusion
#- remote code execution
#- " sudo "
#- " suid "
#- " UAC "
#- docker
#- kubernetes
#- " lxc "

DESCRIPTION_KEYWORDS:
#- User Account Control
#- LFI
#- RCE
#- RFI
#- SQLi

PRODUCT_KEYWORDS_I:
- kubernetes
- Microsoft O365
- web application
- linux
- windows
- macos

PRODUCT_KEYWORDS:
- Aruba Networks  
- Atlassian  
- ByteDance  
- Cisco  
- Clickup  
- Confluence  
- CrowdStrike  
- Docker  
- Forcepoint  
- Fortinet  
- Google  
#- Juniper  
- LanscopeCat  
- Microsoft  
#- Microsoft Exchange  
#- Microsoft SQL  
- Miradore  
- Palo Alto Networks  
- Passbolt  
- PortSwigger  
- Putty  
- Slack  
#- SwaggerUI  
#- Symantec Endpoint  
- Teamvault  
#- Trend Micro  
- VMware  
- VMware Horizon  
- Wazuh  
- Zabbix  
- Zscaler 

# Repo's to exclude when crafting the Github CVE search URL
GITDORK_REPO_EXCLUSIONS:
- CVEProject/cvelist
- CVEProject/cvelistV5
- EXP-Tools/threat-broadcast
- Nazicc/threat-broadcast
- cloudsecurityalliance/gsd-database
- oasis-open/cti-stix-common-objects
- olbat/nvdcve
- ChuntBot/FeedArchive
- nomi-sec/NVD-Database
- github/advisory-database
- goncalor/cve-ark
- tholian-network/vulnerabilities
- sthagen/CVEProject-cvelist
- trickest/cve
- Patrowl/PatrowlHearsData
- aquasecurity/vuln-list-nvd
- bitfront-se/vuln-list-temp
- justakazh/CVE_Database
- khulnasoft-lab/vuln-list-nvd
- adminlove520/treat_v1.0.2
